package indi.qsq.json.api;

/**
 * Created on 2022/8/27.
 */
public enum FlagStyle {

    CONCAT_COMMA, CONCAT_COMMA_SPACE, CONCAT_SPACE, CONCAT_LINE_FEED,
    CONCAT_PLUS, CONCAT_PLUS_SPACE, CONCAT_AMPERSAND, CONCAT_AMPERSAND_SPACE, CONCAT_VERTICAL_BAR, CONCAT_VERTICAL_BAR_SPACE,
    JSON_ARRAY, JSON_ARRAY_WITH_REMAIN, JSON_OBJECT, JSON_OBJECT_WITH_REMAIN;

    private static final long serialVersionUID = 0x516F049C0AAA3A12L;
}
