package mujica.io.codec;

import mujica.algebra.random.RandomContext;
import mujica.reflect.modifier.CodeHistory;
import org.jetbrains.annotations.NotNull;
import org.junit.Assert;
import org.junit.Test;

import java.nio.charset.StandardCharsets;

@SuppressWarnings("SpellCheckingInspection")
@CodeHistory(date = "2026/2/14")
public class PercentCharsetTest {

    private static final int REPEAT = 2075;

    private final RandomContext rc = new RandomContext();

    private final UriCharset uriCharset = new UriCharset(true);

    private void caseUriOnce(@NotNull String original, @NotNull String encoded) {
        Assert.assertEquals(encoded, new String(original.getBytes(uriCharset), StandardCharsets.US_ASCII)); // encode
        Assert.assertEquals(original, new String(encoded.getBytes(StandardCharsets.US_ASCII), uriCharset)); // decode
    }

    private void caseUri(@NotNull String original, @NotNull String encoded) {
        caseUriOnce(original, encoded);
        final int repeat = rc.nextInt(2, REPEAT);
        caseUriOnce(original.repeat(repeat), encoded.repeat(repeat));
    }

    @Test
    public void caseUri1() {
        caseUri(
                "$",
                "$"
        );
        caseUri(
                "3.3",
                "3.3"
        );
        caseUri(
                "2026",
                "2026"
        );
        caseUri(
                "plane",
                "plane"
        );
        caseUri(
                "16300+2905",
                "16300+2905"
        );
        caseUri(
                "9830405724649641",
                "9830405724649641"
        );
        caseUri(
                "58223114633A9F1Ec5bd7123940460dd",
                "58223114633A9F1Ec5bd7123940460dd"
        );
        caseUri(
                "share,shade,shave,shape,shake,shame",
                "share,shade,shave,shape,shake,shame"
        );
        caseUri(
                "DIRECTIONALITY_POP_DIRECTIONAL_ISOLATE;",
                "DIRECTIONALITY_POP_DIRECTIONAL_ISOLATE;"
        );
    }

    @Test
    public void caseUri2() {
        // generated by Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36
        caseUri(
                "\\",
                "%5C"
        );
        caseUri(
                "~!@#$%^&*()_+",
                "~!@#$%25%5E&*()_+"
        );
        caseUri(
                "rm -rf /",
                "rm%20-rf%20/"
        );
        caseUri(
                "[<scheme>:]<scheme-specific-part>[#<fragment>]",
                "%5B%3Cscheme%3E:%5D%3Cscheme-specific-part%3E%5B#%3Cfragment%3E%5D"
        );
        caseUri(
                "<fileNamePattern>${LOG_HOME}mylog-%d{yyyy-MM-dd}.%i.log</fileNamePattern>",
                "%3CfileNamePattern%3E$%7BLOG_HOME%7Dmylog-%25d%7Byyyy-MM-dd%7D.%25i.log%3C/fileNamePattern%3E"
        );
    }

    @Test
    public void caseUri3() {
        // generated by Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36
        caseUri(
                "王",
                "%E7%8E%8B"
        );
        caseUri(
                "naïve",
                "na%C3%AFve"
        );
        caseUri(
                "联通",
                "%E8%81%94%E9%80%9A"
        );
        caseUri(
                "Erwin Schrödinger",
                "Erwin%20Schr%C3%B6dinger"
        );
        caseUri(
                "火龙果",
                "%E7%81%AB%E9%BE%99%E6%9E%9C"
        );
        caseUri(
                "Припять", // Prypiat
                "%D0%9F%D1%80%D0%B8%D0%BF%D1%8F%D1%82%D1%8C"
        );
        caseUri(
                "Спутник", // Sputnik
                "%D0%A1%D0%BF%D1%83%D1%82%D0%BD%D0%B8%D0%BA"
        );
        caseUri(
                "Πυθαγόρας", // Pythagoras
                "%CE%A0%CF%85%CE%B8%CE%B1%CE%B3%CF%8C%CF%81%CE%B1%CF%82"
        );
        caseUri(
                "Ἀπολλώνιος", // Apollonius
                "%E1%BC%88%CF%80%CE%BF%CE%BB%CE%BB%CF%8E%CE%BD%CE%B9%CE%BF%CF%82"
        );
        caseUri(
                "无可奈何花落去",
                "%E6%97%A0%E5%8F%AF%E5%A5%88%E4%BD%95%E8%8A%B1%E8%90%BD%E5%8E%BB"
        );
        caseUri(
                "Владивосток", // Vladivostok
                "%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%B2%D0%BE%D1%81%D1%82%D0%BE%D0%BA"
        );
        caseUri(
                "Лубянская площадь", // 卢比扬卡
                "%D0%9B%D1%83%D0%B1%D1%8F%D0%BD%D1%81%D0%BA%D0%B0%D1%8F%20%D0%BF%D0%BB%D0%BE%D1%89%D0%B0%D0%B4%D1%8C"
        );
        caseUri(
                "ΚλαύδιοςΠτολεμαῖος", // Claudius Ptolemaeus
                "%CE%9A%CE%BB%CE%B1%CF%8D%CE%B4%CE%B9%CE%BF%CF%82%CE%A0%CF%84%CE%BF%CE%BB%CE%B5%CE%BC%CE%B1%E1%BF%96%CE%BF%CF%82"
        );
        caseUri(
                "天若有情天亦老，人间正道是沧桑。",
                "%E5%A4%A9%E8%8B%A5%E6%9C%89%E6%83%85%E5%A4%A9%E4%BA%A6%E8%80%81%EF%BC%8C%E4%BA%BA%E9%97%B4%E6%AD%A3%E9%81%93%E6%98%AF%E6%B2%A7%E6%A1%91%E3%80%82"
        );
    }

    private final UriComponentCharset uriComponentCharset = new UriComponentCharset(true);

    private void caseUriComponentOnce(@NotNull String original, @NotNull String encoded) {
        Assert.assertEquals(encoded, new String(original.getBytes(uriComponentCharset), StandardCharsets.US_ASCII)); // encode
        Assert.assertEquals(original, new String(encoded.getBytes(StandardCharsets.US_ASCII), uriComponentCharset)); // decode
    }

    private void caseUriComponent(@NotNull String original, @NotNull String encoded) {
        caseUriComponentOnce(original, encoded);
        final int repeat = rc.nextInt(2, REPEAT);
        caseUriComponentOnce(original.repeat(repeat), encoded.repeat(repeat));
    }

    @Test
    public void caseUriComponent1() {
        caseUriComponent(
                "!",
                "!"
        );
        caseUriComponent(
                "zombie",
                "zombie"
        );
        caseUriComponent(
                "(reserved)",
                "(reserved)"
        );
        caseUriComponent(
                "9830405724649641*49932",
                "9830405724649641*49932"
        );
        caseUriComponent(
                "MIN_SUPPLEMENTARY_CODE_POINT",
                "MIN_SUPPLEMENTARY_CODE_POINT"
        );
        caseUriComponent(
                "sound-wound-found-bound-hound-round-pound",
                "sound-wound-found-bound-hound-round-pound"
        );
    }

    @Test
    public void caseUriComponent2() {
        // generated by Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36
        caseUriComponent(
                "#",
                "%23"
        );
        caseUriComponent(
                ":)",
                "%3A)"
        );
        caseUriComponent(
                "{@code UPPERCASE_LETTER}",
                "%7B%40code%20UPPERCASE_LETTER%7D"
        );
        caseUriComponent(
                "ALIBABA (CHINA) NETWORK TECHNOLOGY CO.,LTD.",
                "ALIBABA%20(CHINA)%20NETWORK%20TECHNOLOGY%20CO.%2CLTD."
        );
        caseUriComponent(
                "if exist \"%TEMP%\\%~nx0.run\" goto mainEntry",
                "if%20exist%20%22%25TEMP%25%5C%25~nx0.run%22%20goto%20mainEntry"
        );
        caseUriComponent(
                "https://hub.docker.com/r/pandas/pandas-gitpod/tags",
                "https%3A%2F%2Fhub.docker.com%2Fr%2Fpandas%2Fpandas-gitpod%2Ftags"
        );
        caseUriComponent(
                "<fileset dir=\"${catalina.home}/lib\" includes=\"*.jar\"/>",
                "%3Cfileset%20dir%3D%22%24%7Bcatalina.home%7D%2Flib%22%20includes%3D%22*.jar%22%2F%3E"
        );
    }

    @Test
    public void caseUriComponent3() {
        // generated by Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36
        caseUriComponent(
                "刀",
                "%E5%88%80"
        );
        caseUriComponent(
                "Skandinaviske halvø", // Scandinavia peninsula
                "Skandinaviske%20halv%C3%B8"
        );
        caseUriComponent(
                "鸿门宴",
                "%E9%B8%BF%E9%97%A8%E5%AE%B4"
        );
        caseUriComponent(
                "[ˈtʊənəmənt]",
                "%5B%CB%88t%CA%8A%C9%99n%C9%99m%C9%99nt%5D"
        );
        caseUriComponent(
                "[ˈθə:məu,steibəlaiˈzeiʃən]",
                "%5B%CB%88%CE%B8%C9%99%3Am%C9%99u%2Csteib%C9%99lai%CB%88zei%CA%83%C9%99n%5D"
        );
        caseUriComponent(
                "一年之计在于春",
                "%E4%B8%80%E5%B9%B4%E4%B9%8B%E8%AE%A1%E5%9C%A8%E4%BA%8E%E6%98%A5"
        );
        caseUriComponent(
                "画虎画皮难画骨，知人知面不知心。",
                "%E7%94%BB%E8%99%8E%E7%94%BB%E7%9A%AE%E9%9A%BE%E7%94%BB%E9%AA%A8%EF%BC%8C%E7%9F%A5%E4%BA%BA%E7%9F%A5%E9%9D%A2%E4%B8%8D%E7%9F%A5%E5%BF%83%E3%80%82"
        );
    }
}
