package mujica.io.codec;

import mujica.algebra.random.RandomContext;
import mujica.reflect.modifier.CodeHistory;
import org.jetbrains.annotations.NotNull;
import org.junit.Assert;
import org.junit.Test;

import java.nio.charset.StandardCharsets;

@SuppressWarnings("SpellCheckingInspection")
@CodeHistory(date = "2026/2/14")
public class PercentCharsetTest {

    private static final int REPEAT = 2075;

    private final RandomContext rc = new RandomContext();

    private final UriCharset uriCharset = new UriCharset(true);

    private void caseUriOnce(@NotNull String original, @NotNull String encoded) {
        Assert.assertEquals(encoded, new String(original.getBytes(uriCharset), StandardCharsets.US_ASCII)); // encode
        Assert.assertEquals(original, new String(encoded.getBytes(StandardCharsets.US_ASCII), uriCharset)); // decode
    }

    private void caseUri(@NotNull String original, @NotNull String encoded) {
        caseUriOnce(original, encoded);
        final int repeat = rc.nextInt(2, REPEAT);
        caseUriOnce(original.repeat(repeat), encoded.repeat(repeat));
    }

    @Test
    public void caseUri1() {
        caseUri(
                "$",
                "$"
        );
        caseUri(
                "3.3",
                "3.3"
        );
        caseUri(
                "2026",
                "2026"
        );
        caseUri(
                "plane",
                "plane"
        );
        caseUri(
                "16300+2905",
                "16300+2905"
        );
        caseUri(
                "9830405724649641",
                "9830405724649641"
        );
        caseUri(
                "58223114633A9F1Ec5bd7123940460dd",
                "58223114633A9F1Ec5bd7123940460dd"
        );
        caseUri(
                "share,shade,shave,shape,shake,shame",
                "share,shade,shave,shape,shake,shame"
        );
        caseUri(
                "DIRECTIONALITY_POP_DIRECTIONAL_ISOLATE;",
                "DIRECTIONALITY_POP_DIRECTIONAL_ISOLATE;"
        );
    }

    @Test
    public void caseUri2() {
        // generated by Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36
        caseUri(
                "\\",
                "%5C"
        );
        caseUri(
                "~!@#$%^&*()_+",
                "~!@#$%25%5E&*()_+"
        );
        caseUri(
                "rm -rf /",
                "rm%20-rf%20/"
        );
        caseUri(
                "[<scheme>:]<scheme-specific-part>[#<fragment>]",
                "%5B%3Cscheme%3E:%5D%3Cscheme-specific-part%3E%5B#%3Cfragment%3E%5D"
        );
        caseUri(
                "<fileNamePattern>${LOG_HOME}mylog-%d{yyyy-MM-dd}.%i.log</fileNamePattern>",
                "%3CfileNamePattern%3E$%7BLOG_HOME%7Dmylog-%25d%7Byyyy-MM-dd%7D.%25i.log%3C/fileNamePattern%3E"
        );
    }

    @Test
    public void caseUri3() {
        // generated by Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36
        caseUri(
                "王",
                "%E7%8E%8B"
        );
        caseUri(
                "naïve",
                "na%C3%AFve"
        );
        caseUri(
                "联通",
                "%E8%81%94%E9%80%9A"
        );
        caseUri(
                "Erwin Schrödinger",
                "Erwin%20Schr%C3%B6dinger"
        );
        caseUri(
                "火龙果",
                "%E7%81%AB%E9%BE%99%E6%9E%9C"
        );
        caseUri(
                "Припять", // Prypiat
                "%D0%9F%D1%80%D0%B8%D0%BF%D1%8F%D1%82%D1%8C"
        );
        caseUri(
                "Спутник", // Sputnik
                "%D0%A1%D0%BF%D1%83%D1%82%D0%BD%D0%B8%D0%BA"
        );
        caseUri(
                "ฅ^•ﻌ•^ฅ",
                "%E0%B8%85%5E%E2%80%A2%EF%BB%8C%E2%80%A2%5E%E0%B8%85"
        );
        caseUri(
                "Πυθαγόρας", // Pythagoras
                "%CE%A0%CF%85%CE%B8%CE%B1%CE%B3%CF%8C%CF%81%CE%B1%CF%82"
        );
        caseUri(
                "Ἀπολλώνιος", // Apollonius
                "%E1%BC%88%CF%80%CE%BF%CE%BB%CE%BB%CF%8E%CE%BD%CE%B9%CE%BF%CF%82"
        );
        caseUri(
                "ㄚㄛㄜㄧㄨㄩㄝ",
                "%E3%84%9A%E3%84%9B%E3%84%9C%E3%84%A7%E3%84%A8%E3%84%A9%E3%84%9D"
        );
        caseUri(
                "无可奈何花落去",
                "%E6%97%A0%E5%8F%AF%E5%A5%88%E4%BD%95%E8%8A%B1%E8%90%BD%E5%8E%BB"
        );
        caseUri(
                "(◍•ᴗ•◍)ﾉ♡",
                "(%E2%97%8D%E2%80%A2%E1%B4%97%E2%80%A2%E2%97%8D)%EF%BE%89%E2%99%A1"
        );
        caseUri(
                "Владивосток", // Vladivostok
                "%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%B2%D0%BE%D1%81%D1%82%D0%BE%D0%BA"
        );
        caseUri(
                "安卓资源打包工具AAPT",
                "%E5%AE%89%E5%8D%93%E8%B5%84%E6%BA%90%E6%89%93%E5%8C%85%E5%B7%A5%E5%85%B7AAPT"
        );
        caseUri(
                "CSGO反恐精英全球攻势",
                "CSGO%E5%8F%8D%E6%81%90%E7%B2%BE%E8%8B%B1%E5%85%A8%E7%90%83%E6%94%BB%E5%8A%BF"
        );
        caseUri(
                "Лубянская площадь", // 卢比扬卡
                "%D0%9B%D1%83%D0%B1%D1%8F%D0%BD%D1%81%D0%BA%D0%B0%D1%8F%20%D0%BF%D0%BB%D0%BE%D1%89%D0%B0%D0%B4%D1%8C"
        );
        caseUri(
                "ΚλαύδιοςΠτολεμαῖος", // Claudius Ptolemaeus
                "%CE%9A%CE%BB%CE%B1%CF%8D%CE%B4%CE%B9%CE%BF%CF%82%CE%A0%CF%84%CE%BF%CE%BB%CE%B5%CE%BC%CE%B1%E1%BF%96%CE%BF%CF%82"
        );
        caseUri(
                "天若有情天亦老，人间正道是沧桑。",
                "%E5%A4%A9%E8%8B%A5%E6%9C%89%E6%83%85%E5%A4%A9%E4%BA%A6%E8%80%81%EF%BC%8C%E4%BA%BA%E9%97%B4%E6%AD%A3%E9%81%93%E6%98%AF%E6%B2%A7%E6%A1%91%E3%80%82"
        );
    }

    @Test
    public void caseUri4() {
        // generated by Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36
        caseUri(
                "\ud86a\udc40\ud86a\udddf\ud86a\udf65", // CJK Extension C
                "%F0%AA%A1%80%F0%AA%A7%9F%F0%AA%AD%A5"
        );
        caseUri(
                "\ud86d\udf32\ud86d\udf3f", // CJK Extension C
                "%F0%AB%9C%B2%F0%AB%9C%BF"
        );
        caseUri(
                "\ud86e\udc2c\ud86e\udc72", // CJK Extension E
                "%F0%AB%A0%AC%F0%AB%A1%B2"
        );
        caseUri(
                "\ud86e\ude5d\ud86e\udf42\ud86e\udf43\ud86e\udf8a", // CJK Extension E
                "%F0%AB%A9%9D%F0%AB%AD%82%F0%AB%AD%83%F0%AB%AE%8A"
        );
        caseUri(
                "\ud873\udeb0\ud873\udeb1", // CJK Extension F
                "%F0%AC%BA%B0%F0%AC%BA%B1"
        );
        caseUri(
                "\ud873\udf05\ud873\udf66\ud874\udc4e", // CJK Extension F
                "%F0%AC%BC%85%F0%AC%BD%A6%F0%AD%81%8E"
        );
        caseUri(
                "\ud880\udc55\ud880\udd7b\ud880\uddb1", // CJK Extension G
                "%F0%B0%81%95%F0%B0%85%BB%F0%B0%86%B1"
        );
        caseUri(
                "\ud881\udc3c\ud881\udc2d\ud881\udc43\ud882\udd5e", // CJK Extension G
                "%F0%B0%90%BC%F0%B0%90%AD%F0%B0%91%83%F0%B0%A5%9E"
        );
        caseUri(
                "\ud884\udd47\ud884\udd50\ud884\ude47", // CJK Extension G
                "%F0%B1%85%87%F0%B1%85%90%F0%B1%89%87"
        );
        caseUri(
                "\ud887\udd81\ud887\udd9a\ud888\udc8d", // CJK Extension H
                "%F0%B1%B6%81%F0%B1%B6%9A%F0%B2%82%8D"
        );
        caseUri(
                "\ud87b\udce8\ud87b\udda1\ud87b\ude5b", // CJK Extension I
                "%F0%AE%B3%A8%F0%AE%B6%A1%F0%AE%B9%9B"
        );
        caseUri(
                "\ud83d\udc5c",
                "%F0%9F%91%9C"
        );
        caseUri(
                "\ud83c\udfb5\ud83c\udfb6\ud83c\udf9b\ufe0f", // the last is a variation selector
                "%F0%9F%8E%B5%F0%9F%8E%B6%F0%9F%8E%9B%EF%B8%8F"
        );
        caseUri(
                "%\ud83c\udf33[\ud83c\udf34]\ud83c\udf35",
                "%25%F0%9F%8C%B3%5B%F0%9F%8C%B4%5D%F0%9F%8C%B5"
        );
        caseUri(
                "放声大哭\ud83d\ude2d",
                "%E6%94%BE%E5%A3%B0%E5%A4%A7%E5%93%AD%F0%9F%98%AD"
        );
        caseUri(
                "\ud83d\ude48非礼勿视",
                "%F0%9F%99%88%E9%9D%9E%E7%A4%BC%E5%8B%BF%E8%A7%86"
        );
        caseUri(
                "\ud83c\udf47\ud83c\udf48\ud83c\udf49\ud83c\udf4a\ud83c\udf4b",
                "%F0%9F%8D%87%F0%9F%8D%88%F0%9F%8D%89%F0%9F%8D%8A%F0%9F%8D%8B"
        );
        caseUri(
                "\ud83c\udf26\ufe0f,\ud83c\udf27\ufe0f;\ud83c\udf28\ufe0f.",
                "%F0%9F%8C%A6%EF%B8%8F,%F0%9F%8C%A7%EF%B8%8F;%F0%9F%8C%A8%EF%B8%8F."
        );
        caseUri(
                "\ud83c\udf6422\ud83c\udf655\ud83e\udd6e80\ud83c\udf611\ud83e\udd5f3",
                "%F0%9F%8D%A422%F0%9F%8D%A55%F0%9F%A5%AE80%F0%9F%8D%A11%F0%9F%A5%9F3"
        );
    }

    private final UriComponentCharset uriComponentCharset = new UriComponentCharset(true);

    private void caseUriComponentOnce(@NotNull String original, @NotNull String encoded) {
        Assert.assertEquals(encoded, new String(original.getBytes(uriComponentCharset), StandardCharsets.US_ASCII)); // encode
        Assert.assertEquals(original, new String(encoded.getBytes(StandardCharsets.US_ASCII), uriComponentCharset)); // decode
    }

    private void caseUriComponent(@NotNull String original, @NotNull String encoded) {
        caseUriComponentOnce(original, encoded);
        final int repeat = rc.nextInt(2, REPEAT);
        caseUriComponentOnce(original.repeat(repeat), encoded.repeat(repeat));
    }

    @Test
    public void caseUriComponent1() {
        caseUriComponent(
                "!",
                "!"
        );
        caseUriComponent(
                "zombie",
                "zombie"
        );
        caseUriComponent(
                "(reserved)",
                "(reserved)"
        );
        caseUriComponent(
                "9830405724649641*49932",
                "9830405724649641*49932"
        );
        caseUriComponent(
                "MIN_SUPPLEMENTARY_CODE_POINT",
                "MIN_SUPPLEMENTARY_CODE_POINT"
        );
        caseUriComponent(
                "sound-wound-found-bound-hound-round-pound",
                "sound-wound-found-bound-hound-round-pound"
        );
    }

    @Test
    public void caseUriComponent2() {
        // generated by Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36
        caseUriComponent(
                "#",
                "%23"
        );
        caseUriComponent(
                ":)",
                "%3A)"
        );
        caseUriComponent(
                "{@code UPPERCASE_LETTER}",
                "%7B%40code%20UPPERCASE_LETTER%7D"
        );
        caseUriComponent(
                "ALIBABA (CHINA) NETWORK TECHNOLOGY CO.,LTD.",
                "ALIBABA%20(CHINA)%20NETWORK%20TECHNOLOGY%20CO.%2CLTD."
        );
        caseUriComponent(
                "if exist \"%TEMP%\\%~nx0.run\" goto mainEntry",
                "if%20exist%20%22%25TEMP%25%5C%25~nx0.run%22%20goto%20mainEntry"
        );
        caseUriComponent(
                "https://hub.docker.com/r/pandas/pandas-gitpod/tags",
                "https%3A%2F%2Fhub.docker.com%2Fr%2Fpandas%2Fpandas-gitpod%2Ftags"
        );
        caseUriComponent(
                "<fileset dir=\"${catalina.home}/lib\" includes=\"*.jar\"/>",
                "%3Cfileset%20dir%3D%22%24%7Bcatalina.home%7D%2Flib%22%20includes%3D%22*.jar%22%2F%3E"
        );
    }

    @Test
    public void caseUriComponent3() {
        // generated by Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36
        caseUriComponent(
                "刀",
                "%E5%88%80"
        );
        caseUriComponent(
                "Skandinaviske halvø", // Scandinavia peninsula
                "Skandinaviske%20halv%C3%B8"
        );
        caseUriComponent(
                "鸿门宴",
                "%E9%B8%BF%E9%97%A8%E5%AE%B4"
        );
        caseUriComponent(
                "TSMC台积电",
                "TSMC%E5%8F%B0%E7%A7%AF%E7%94%B5"
        );
        caseUriComponent(
                "[ˈtʊənəmənt]",
                "%5B%CB%88t%CA%8A%C9%99n%C9%99m%C9%99nt%5D"
        );
        caseUriComponent(
                "(；´д｀)ゞ",
                "(%EF%BC%9B%C2%B4%D0%B4%EF%BD%80)%E3%82%9E"
        );
        caseUriComponent(
                "一年之计在于春",
                "%E4%B8%80%E5%B9%B4%E4%B9%8B%E8%AE%A1%E5%9C%A8%E4%BA%8E%E6%98%A5"
        );
        caseUriComponent(
                "[ˈθə:məu,steibəlaiˈzeiʃən]",
                "%5B%CB%88%CE%B8%C9%99%3Am%C9%99u%2Csteib%C9%99lai%CB%88zei%CA%83%C9%99n%5D"
        );
        caseUriComponent(
                "✧⁺⸜(●˙▾˙●)⸝⁺✧",
                "%E2%9C%A7%E2%81%BA%E2%B8%9C(%E2%97%8F%CB%99%E2%96%BE%CB%99%E2%97%8F)%E2%B8%9D%E2%81%BA%E2%9C%A7"
        );
        caseUriComponent(
                "濒危野生动植物种国际贸易公约CITES",
                "%E6%BF%92%E5%8D%B1%E9%87%8E%E7%94%9F%E5%8A%A8%E6%A4%8D%E7%89%A9%E7%A7%8D%E5%9B%BD%E9%99%85%E8%B4%B8%E6%98%93%E5%85%AC%E7%BA%A6CITES"
        );
        caseUriComponent(
                "画虎画皮难画骨，知人知面不知心。",
                "%E7%94%BB%E8%99%8E%E7%94%BB%E7%9A%AE%E9%9A%BE%E7%94%BB%E9%AA%A8%EF%BC%8C%E7%9F%A5%E4%BA%BA%E7%9F%A5%E9%9D%A2%E4%B8%8D%E7%9F%A5%E5%BF%83%E3%80%82"
        );
    }

    @Test
    public void caseUriComponent4() {
        // generated by Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36
        caseUriComponent(
                "\ud869\udf00\ud869\udf0d", // CJK Extension C
                "%F0%AA%9C%80%F0%AA%9C%8D"
        );
        caseUriComponent(
                "\ud86c\uddb3\ud86c\uddda\ud86c\udea5\ud86d\udddf", // CJK Extension C
                "%F0%AB%86%B3%F0%AB%87%9A%F0%AB%8A%A5%F0%AB%97%9F"
        );
        caseUriComponent(
                "\ud86e\udd78\ud86e\udd71\ud86e\ude6e", // CJK Extension E
                "%F0%AB%A5%B8%F0%AB%A5%B1%F0%AB%A9%AE"
        );
        caseUriComponent(
                "\ud873\udeb0\ud873\udeb1", // CJK Extension F
                "%F0%AC%BA%B0%F0%AC%BA%B1"
        );
        caseUriComponent(
                "\ud875\udedc\ud877\ude21\ud877\ude36\ud87a\udd2b", // CJK Extension F
                "%F0%AD%9B%9C%F0%AD%B8%A1%F0%AD%B8%B6%F0%AE%A4%AB"
        );
        caseUriComponent(
                "\ud880\udc55\ud880\udd7b\ud880\uddb1", // CJK Extension G
                "%F0%B0%81%95%F0%B0%85%BB%F0%B0%86%B1"
        );
        caseUriComponent(
                "\ud884\udd3f\ud884\udd59", // CJK Extension G
                "%F0%B1%84%BF%F0%B1%85%99"
        );
        caseUriComponent(
                "\ud884\udfaa\ud885\ude75", // CJK Extension H
                "%F0%B1%8E%AA%F0%B1%99%B5"
        );
        caseUriComponent(
                "\ud887\udc7a\ud887\udc83\ud888\udebe", // CJK Extension H
                "%F0%B1%B1%BA%F0%B1%B2%83%F0%B2%8A%BE"
        );
        caseUriComponent(
                "\ud87a\udff0\ud87a\udff7", // CJK Extension I
                "%F0%AE%AF%B0%F0%AE%AF%B7"
        );
        caseUriComponent(
                "OK\ud83d\udc4c",
                "OK%F0%9F%91%8C"
        );
        caseUriComponent(
                "\ud83c\udf00\ud83c\udf08",
                "%F0%9F%8C%80%F0%9F%8C%88"
        );
        caseUriComponent(
                "给我打电话\ud83e\udd19",
                "%E7%BB%99%E6%88%91%E6%89%93%E7%94%B5%E8%AF%9D%F0%9F%A4%99"
        );
        caseUriComponent(
                "\ud83d\ude4f双手合十（希望人没事）",
                "%F0%9F%99%8F%E5%8F%8C%E6%89%8B%E5%90%88%E5%8D%81%EF%BC%88%E5%B8%8C%E6%9C%9B%E4%BA%BA%E6%B2%A1%E4%BA%8B%EF%BC%89"
        );
        caseUriComponent(
                "\ud83d\ude08+\ud83d\udc7f=?",
                "%F0%9F%98%88%2B%F0%9F%91%BF%3D%3F"
        );
        caseUriComponent(
                "\ud83d\udc68\u200d\ud83c\udf3e\ud83d\udc69\u200d\ud83c\udf3e",
                "%F0%9F%91%A8%E2%80%8D%F0%9F%8C%BE%F0%9F%91%A9%E2%80%8D%F0%9F%8C%BE"
        );
        caseUriComponent(
                "\ud83d\udea8A\ud83d\udea5B\ud83d\udea6C\ud83d\uded1D\ud83d\udea7E",
                "%F0%9F%9A%A8A%F0%9F%9A%A5B%F0%9F%9A%A6C%F0%9F%9B%91D%F0%9F%9A%A7E"
        );
        caseUriComponent(
                "\ud83d\udc68\u200d\ud83d\udc69\u200d\ud83d\udc66 \ud83d\udc68\u200d\ud83d\udc69\u200d\ud83d\udc67",
                "%F0%9F%91%A8%E2%80%8D%F0%9F%91%A9%E2%80%8D%F0%9F%91%A6%20%F0%9F%91%A8%E2%80%8D%F0%9F%91%A9%E2%80%8D%F0%9F%91%A7"
        );
    }
}
